openapi: 3.0.0
info:
  description: |-
    This is the Urgent and Emergency Care Booking API, you can find out more at the
        [NHS Digital API Hub](https://developer.nhs.uk/apis/uec-appointments)
  version: 2.0.0
  title: Care Connect API
  termsOfService: https://developer.nhs.uk/apis/uec-appointments
  contact:
    email: uec.appointmentbooking@nhs.net
    url: https://developer.nhs.uk/apis/uec-appointments
    name: NHS Digital
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: https://dev-uae.api.nhs.uk/v2/
    description: Dev
tags:
  - name: Foundation
    description: ''
  - name: Appointment
    description: A booking of a healthcare event
    externalDocs:
      url: https://developer.nhs.uk/apis/nhsbooking-2.0.0-beta/book_an_appointment.html
  - name: Slot
    description: A Slot into which an Appointment can be booked
    externalDocs:
      url: https://developer.nhs.uk/apis/nhsbooking-2.0.0-beta/search_free_slots.html
      
security: 
  - BasicAuth: []
  - BearerAuth: []
  
paths:
  /metadata:

    #Common parameters for /metadata
    parameters:
    - $ref: '#/components/parameters/Ssp-TraceIDParam'
    - $ref: '#/components/parameters/Ssp-FromParam'
    - $ref: '#/components/parameters/Ssp-ToParam'
    - $ref: '#/components/parameters/Ssp-InteractionIDParam'
    - $ref: '#/components/parameters/Authorisation_Param'
    
    get:
      tags:
        - Foundation
      summary: Get the FHIR capability statement
      description: Get the FHIR capability statement

        
      operationId: getMetaData


      responses:
        '200':
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/Capability'
            
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/Capability'

                  
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  


  /slot:
    parameters:
      - $ref: '#/components/parameters/Ssp-TraceIDParam'
      - $ref: '#/components/parameters/Ssp-FromParam'
      - $ref: '#/components/parameters/Ssp-ToParam'
      - $ref: '#/components/parameters/Ssp-InteractionIDParam'
      - $ref: '#/components/parameters/Authorisation_Param'  
  
    get:
      tags:
        - Slot
      summary: Search for free slots 
      description: Search for free slots based on the criteria provided
      externalDocs: 
        url: 'https://developer.nhs.uk/apis/nhsbooking-2.0.0-beta/search_free_slots.html'
        
      operationId: getSlots
      
      parameters:
        - name: healthcareService
          description: The  service id of the service for which Slots are being requested
          in: query
          schema:
            type: string
            example: 09a01679-2564-0fb4-5129-aecc81ea2706
          required: true
          allowEmptyValue: false
          
          
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - free
                - busy
              default: free
              
        - name: start
          in: query
          required: true
          description: |
            Slot end date/time (yyyy-mm-ddThh:mm:ss+hh:mm)
            
            __Start and end represent the definition of the time window within which Slots must start__
          schema:
            format: datetime
            type: string
            example: '2020-03-31T14:00:00'        
              
        - name: end
          in: query
          required: true
          description: |
            Slot end date/time (yyyy-mm-ddThh:mm:ss+hh:mm)
            
            __Start and end represent the definition of the time window within which Slots must start__
          schema:
            format: datetime
            type: string
            example: '2020-03-31T16:00:00'    
        
        - name: inclusions
          in: query
          description: | 
            Inclusions that drive the rescusive depth of the search
    
            |Inclusion           |Description|
            |-------             | --------|
            | Schedule           | Include Schedule Resources referenced within the  Slot Resources|
            | Practitioner       | Include Practitioner Resources referenced within the  Schedule Resources|
            | PractitionerRole   | Include Practitioner Role Resources referenced within the  Schedule Resources |
            | HealthcareService  | Include HealthcareService Resources referenced within the  Schedule Resources|
            | ProvidedBy         | Include Organization Resources referenced within the  HealthcareService Resources|
            | Location           | Include Location Resources referenced within the  HealthcareService Resources|
            


          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - Schedule
                - Practitioner
                - PractitionerRole
                - HealthcareService
                - ProvidedBy
                - Location
      
    
              
      responses:
        '200':
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/SlotBundle'

            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/SlotBundle'
                  
                  
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  
          
  /appointment:
    
    #Common parameters for /appointment
    parameters:
      - $ref: '#/components/parameters/Ssp-TraceIDParam'
      - $ref: '#/components/parameters/Ssp-FromParam'
      - $ref: '#/components/parameters/Ssp-ToParam'
      - $ref: '#/components/parameters/Ssp-InteractionIDParam'
      - $ref: '#/components/parameters/Authorisation_Param'
    
    get:
      tags:
        - Appointment
      summary: Get the appointments for a sepecific patient 
      description: Get the appointments for a sepecific patient 

        
      operationId: getAppointments
      parameters:
        - name: patientId
          description: The national service identifier of the Patient for whom Appointments are being requested.

          in: query
          schema:
            type: string
            example: 09a01679-2564-0fb4-5129-aecc81ea2706
          required: true
          allowEmptyValue: false
          
          
        - name: status
          in: query
          description: Appointment status values should be included in the result set
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - free
                - busy
              default: free
              
        - name: from
          in: query
          required: false
          description: Point in time to search from (yyyy-mm-ddThh:mm:ss+hh:mm)
          schema:
            format: datetime
            type: string
            example: '2020-03-31T14:00:00'        
              
        - name: to
          in: query
          required: false
          description: Point in time to search to (yyyy-mm-ddThh:mm:ss+hh:mm)
          schema:
            format: datetime
            type: string
            example: '2020-03-31T16:00:00'    
        

      responses:
        '200':
          description: Success
          content:
            application/fhir+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
            
            application/fhir+xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'

                  
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  
          
    post:
      tags:
        - Appointment
      summary: Create an appointment for a sepecific patient 
      description: Craete an appointment for a sepecific patient 
      operationId: createAppointment
      
      requestBody:
        description: Appointment Deatils
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/Appointment'
          
          application/fhir+xml:
            schema:
              $ref: '#/components/schemas/Appointment'
              
      responses:
        '201':
          description: Success

        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  
  /appointment/{appointmentId}:
  
    #Common parameters for /appointment/(appointmentId)
    parameters:
      - $ref: '#/components/parameters/Ssp-TraceIDParam'
      - $ref: '#/components/parameters/Ssp-FromParam'
      - $ref: '#/components/parameters/Ssp-ToParam'
      - $ref: '#/components/parameters/Ssp-InteractionIDParam'
      - $ref: '#/components/parameters/Authorisation_Param'
  
  
    get:
      tags:
        - Appointment
      summary: Get a specific appointment 
      description: Get a specific appointment 

        
      operationId: getAppointment
      parameters:
        - $ref: '#/components/parameters/Appointment_Param'

      responses:
        '200':
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/Appointment'
          
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/Appointment'

        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  
          

  /appointment/{appointmentId}/history/{versionId}:
    #Common parameters for /appointment/(appointmentId)/history
    parameters:
      - $ref: '#/components/parameters/Ssp-TraceIDParam'
      - $ref: '#/components/parameters/Ssp-FromParam'
      - $ref: '#/components/parameters/Ssp-ToParam'
      - $ref: '#/components/parameters/Ssp-InteractionIDParam'
      - $ref: '#/components/parameters/Authorisation_Param'
  
  
    get:
      tags:
        - Appointment
      summary: Get the specific version of an appointment 
      description: Get the specific version of an appointment

        
      operationId: getAppointmentVersion
      parameters:
        - $ref: '#/components/parameters/Appointment_Param'
          
        - name: versionId
          description: The version identifier for the Appointment are being requested.

          in: path
          schema:
            type: string
            example: 2
          required: true
          allowEmptyValue: false

      responses:
        '200':
          description: Success
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/Appointment'
            application/fhir+xml:
              schema:
                $ref: '#/components/schemas/Appointment'


        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  
          
   


            
            
components:
  parameters:
    Ssp-TraceIDParam:
      deprecated: false
      name: 'sspTraceID'
      description: |
        Consumer trace identifier
      schema:
        type: string
        example: 09a01679-2564-0fb4-5129-aecc81ea2706
      in: header
      required: true
    
    Ssp-FromParam:
      deprecated: false
      example: 200000000359
      name: 'sspFrom'
      description: 'Consumer ASID   '
      schema:
        type: string
        example: 200000000359
      in: header
      required: true
      x-last-modified: 1605027259149    
      
    Ssp-ToParam:
      deprecated: false
      example: 918999198993
      name: 'sspTo'
      description: 'Provider ASID '
      schema:
        type: string
        example: 918999198993
      in: header
      required: true
      x-last-modified: 1605017373138
      
    Ssp-InteractionIDParam:
      deprecated: false
      example: ' urn:nhs:names:services:careconnect:fhir:rest:read:metadata-1 '
      name: 'sspInteractionID'
      description: SDS interaction identifier
      schema:
        type: string
        example: ' urn:nhs:names:services:careconnect:fhir:rest:read:metadata-1 '
      in: header
      required: true
      x-last-modified: 1605017420745
    
    Authorisation_Param:
      name: 'authorisationToken'
      in: header       
      description: JWT authorisation header parameter
      schema:
        type: string
        example: '{todo: Create example JWT}'
      required: true
 
    Appointment_Param:     
      name: appointmentId
      description: The identifier of the Appointment.
      in: path
      schema:
        type: string
        example: 09a01679-2564-0fb4-5129-aecc81ea2706
      required: true
      allowEmptyValue: false      
      
  responses:
    '400':
      description: Illegal input for operation.

      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationalOutcome'
            

    '401':
      description: Unauthorized access.

      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationalOutcome'

    '403':
      description: Entity not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationalOutcome'

    '404':
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationalOutcome'
        
    '500':
      description: Server Error

      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OperationalOutcome'
            
            
  schemas:
    
    OperationalOutcome:
      type: object
      example:
        resourceType: OperationOutcome
        meta:
          profile:
            - 'http://hl7.org/fhir/STU3/operationoutcome'
        issue:
          - severity: error
            code: invalid
            details:
              coding:
                - system: 'https://fhir.nhs.uk/STU3/ValueSet/Spine-ErrorOrWarningCode-1'
                  code: BAD_REQUEST
            diagnostics: Any further internal debug details i.e. stack trace details etc.
        
    Capability:
      type: object
      example: 
        resourceType: CapabilityStatement
        version: 2.0.0
        name: Care Connect
        status: active
        date: '2020-02-23'
        publisher: Not provided
        contact:
          - name: NHS Digital
        description: This server implements the Care Connect API version 2.0.0
        copyright: Copyright NHS Digital 2020
        kind: capability
        software:
          name: HAPI FHIR Server
          version: 3.0.0
          releaseDate: '2017-09-27T00:00:00+01:00'
        fhirVersion: 3.0.1
        acceptUnknown: both
        format:
          - application/fhir+json
          - application/fhir+xml
        profile:
          - reference: 'https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Appointment-1'
          - reference: 'https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Slot-1'
        rest:
          - mode: server
            security:
              cors: true
            resource:
              - type: Appointment
                interaction:
                  - code: read
                  - code: create
                  - code: update
                  - code: search-type
                updateCreate: false
                searchParam:
                  - name: identifier
                    type: token
                    documentation: 'NHS Number (i.e. https://fhir.nhs.uk/Id/nhs-number|123456789)'
              - type: Slot
                interaction:
                  - code: search-type
                searchInclude:
                  - 'Schedule:actor:Location'
                  - 'Schedule:actor:Practitioner'
                  - 'Slot:schedule'
                  - 'Location:managingOrganization'
                searchParam:
                  - name: start
                    type: date
                  - name: end
                    type: date
                  - name: status
                    type: token
                  - name: searchFilter
                    type: token
      
    Appointment:
      type: object
      example: 
        resourceType: Appointment
        id: cfd9eba2-cc66-4195-a70c-10112ab1c838
        meta:
          versionId: '2'
          profile:
            - 'https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Appointment-1'
        language: en
        text:
          status: generated
          div: Appointment
        contained:
          - resourceType: DocumentReference
            id: '123'
            meta:
              profile:
                - 'https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-DocumentReference-1'
            identifier:
              - system: 'https://tools.ietf.org/html/rfc4122'
                value: 6b9c59dd-675b-4026-98db-f608ef501e6e
            status: current
            type:
              coding:
                - system: 'urn:oid:2.16.840.1.113883.2.1.3.2.4.18.17'
                  code: POCD_MT200001GB02
                  display: Integrated Urgent Care Report
            indexed: '2018-12-20T09:43:41+11:00'
            content:
            - attachment:
                contentType: application/hl7-v3+xml
                language: en
          - resourceType: Patient
            id: P1
            meta:
              profile:
                - 'https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Patient-1'
            identifier:
            - extension:
                - url: 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSNumberVerificationStatus-1'
                  valueCodeableConcept:
                    coding:
                      - system: 'https://fhir.hl7.org.uk/STU3/CodeSystem/CareConnect-NHSNumberVerificationStatus-1'
                        code: '01'
                        display: Number present and verified
              use: official
              system: 'https://fhir.nhs.uk/Id/nhs-number'
              value: '1234554321'
            name:
              - use: official
                family: Chalmers
                given:
                  - Peter
                prefix:
                  - Mr
            telecom:
              - system: phone
                value: 01234 567 890
                use: home
                rank: 1
            gender: male
            birthDate: '1974-12-25'
            address:
              - use: home
                text: '123 High Street, Leeds LS1 4HR'
                line:
                  - 123 High Street
                  - Leeds
                city: Leeds
                postalCode: LS1 4HR
          - resourceType: Slot
            id: slot002
            identifier:
              - system: 'https://tools.ietf.org/html/rfc4122'
                value: 1db79eb3-72f8-4569-a8dc-af8759797e0f
            schedule:
              reference: Schedule/sched1111
            status: busy
            start: '2019-01-17T15:00:00.000Z'
            end: '2019-01-17T15:30:00.000Z'
        status: booked
        description: Reason for calling
        supportingInformation:
          - reference: '#123'
        start: '2019-01-17T15:00:00.000Z'
        end: '2019-01-17T15:10:00.000Z'
        slot:
          - reference: '#slot002'
        created: '2019-01-17T14:32:22.579+00:00'
        participant:
          - actor:
              reference: '#P1'
              identifier:
                use: official
                system: 'https://fhir.nhs.uk/Id/nhs-number'
                value: '1234554321'
              display: Peter James Chalmers
            status: accepted
      
    
  
    SlotBundle:
      type: object
      example:
        resourceType: Bundle
        id: a56382a1-dce2-483a-8426-65b727b66809
        meta:
          lastUpdated: '2019-05-09T09:26:12.010+00:00'
        type: searchset
        total: 1
        link:
          - relation: self
            url: 'http://a2sibookingprovidertest.directoryofservices.nhs.uk:443/poc/Slot?_format=json&_include=Slot%3Aschedule&_include=Schedule%3Aactor%3APractitioner&_include=Schedule%3Aactor%3APractitionerRole&_include=Schedule%3Aactor%3AHealthcareService&_include=HealthcareService.location&schedule.actor%3Ahealthcareservice=918999198999&start=ge2019-05-09T10%3A00%3A00%2000%3A00&start=le2019-05-09T10%3A30%3A00%2000%3A00&status=free'
        entry:
        - fullUrl: 'http://a2sibookingprovidertest.directoryofservices.nhs.uk:443/poc/Slot/slot005'
          resource:
            resourceType: Slot
            id: slot005
            meta:
              profile:
                - 'https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Slot-1'
            identifier:
              - system: 'https://tools.ietf.org/html/rfc4122'
                value: 5a889965-3db4-4c29-8003-676c247a763e
            schedule:
              reference: Schedule/sched1111
            status: free
            start: '2019-05-09T10:00:00.000+00:00'
            end: '2019-05-09T10:15:00.000+00:00'

  
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    
    BearerAuth:
      type: http
      scheme: bearer